### ISSUE TITLE
Collect new metrics

### ISSUE THREAD

**Issue by leticiasilvazup** [ZupIT/ritchie-cli#489]
**What would you like to be added**:

Collect the following **anonymous** metrics:

- [x] Users that choose to add the community repository and who don't > #517 

- [ ] Users that agree to contribute with data anonimously > #537 

- [x] Used command prompts > #529 

- [x] Commands runtime > #523 

- [x] Where the commands executed are hosted (repository)? > #532

**Why is this needed**:

Better use analyses to show Ritchie's adoption and improve the product

**Comment by victor-schumacher** [comment]
Hi @leticiasilvazup , thanks for the suggestion.
I created a checklist below, so i can tag pull requests on it.

___ 

- [x] Users that choose to add the community repository and who don't

- [x] Users that agree to contribute with data anonimously
 We already have this data, each userID represents a user who agrees to contribute
- [x] Used command prompts

- [x] Commands runtime

- [x] Where the commands executed are hosted (repository)?
