### ISSUE TITLE
Switch the command context for environment

### ISSUE THREAD

**Issue by leticiasilvazup** [ZupIT/ritchie-cli#554]
**What would you like to be added**:

Work on the context command switching it to environments,

**Why is this needed**:

To match the market and Ritchie Cloud

### Tasks

- [x] Remove the current `env` package (#681)
- [x] Move the `rcontext` to new `env` package (#687)
- [x] Edit all variable and methods named `context` inside `rcontext` package (#687)
- [x] Create command `rit set env` (#688)
- [x] Deprecate command `rit set context` (#688)
- [x] Create command `rit show env` (#691)
- [x] Deprecate command `rit show context` (#691)
- [x] Create command `rit delete env` (#694)
- [x] Deprecate command `rit delete context` (#694)
- [x] Convert the file `contexts` to `envs` (#697)
- [ ] Update documentation

**Comment by kaduartur** [comment]
### Tasks

- [ ] Remove the current `env` package
- [ ] Move the `rcontext` to new `env` package
- [ ] Edit all variable and methods named `context` inside `rcontext` package
- [ ] Create command `rit set env`
- [ ] Create command `rit delete env`
- [ ] Create command `rit show env`
- [ ] Deprecate command `rit set context`
- [ ] Deprecate command `rit delete context`
- [ ] Deprecate command `rit show context`
- [ ] Convert the file `contexts` to `envs`
