### ISSUE TITLE
Remove the necessity to copy formulas to tmp dir

### ISSUE THREAD

**Issue by kaduartur** [ZupIT/ritchie-cli#773]
**What would you like to be added**:

We saw that it is no longer necessary to copy the `/bin` folder to a `/tmp` folder, thus reducing I/O when executing formulas.

#### Tasks
- [x] Remove copy in local execution
- [x] Remove copy in docker execution
- [x] Remove post runner function
- [x] Move delete .env file to docker runner
