### ISSUE TITLE
Tests with Testify in Pkg/Cmd

### ISSUE THREAD

**Issue by brunasilvazup** [ZupIT/ritchie-cli#776]
**What would you like to be added**:
- [x] Add repo
- [x] Add workspace // Aron #809 
- [ ] Add
- [ ] Autocomplete
- [ ] Build formula
- [ ] Build
- [x] Create formula // Kadu #805 
- [ ] Create
- [x] Delete credential // Henrique #774 
- [x] Delete env // Bruna #822
- [ ] Delete formula
- [x] Delete repo  // Fernando #908 
- [ ] Delete
- [x] Delete workspace // Henrique #832
- [ ] Formula
- [ ] Init
- [ ] List credential
- [ ] List repo
- [ ] List
- [ ] List workspace
- [ ] Metrics
- [ ] Root
- [x] Set credential // Henrique #824
- [x] Set env // Fernando #926 
- [x] Set formula runner // Henrique #836
- [ ] Set priority
- [ ] Set
- [ ] Show env
- [ ] Show formula runner
- [ ] Show
- [x] Tutorial // Henrique #846
- [ ] Update repo
- [ ] Update
- [ ] Upgrade

**Why is this needed**:
